baseURL = 'https://github.com/Joao-L-S-Almeida/joaolsalmeida.github.io'
languageCode = 'en-us'
title = 'My Archive'
theme = 'ananke'
featured_image = '/images/images_6.jpg' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

#[menu]
#[[menu.main]]
#    identifier = 'blog'
#    name = 'Blog'
#    url = '/posts/'
#    weight = 2
