baseURL = 'https://github.com/Joao-L-S-Almeida/joaolsalmeida.github.io'
languageCode = 'en-us'
title = 'My Archive'
theme = 'ananke'
featured_image = '/images/images_6.jpg' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'
[outputs]
  home = ['html', 'rss']
[menu]
[[menu.main]]
    identifier = 'rss'
    name = 'RSS'
    url = 'https://joao-l-s-almeida.github.io/index.xml'
    weight = 2
